name: ARM-2024-high-latitude-dev
channels:
  - conda-forge
dependencies:
  - jupyter-book
  - jupyterlab
  - sphinx-pythia-theme
  - xarray
  - arm_pyart
  - act-atmos
  - dask
  - dask-labextension
  - xradar
